### ISSUE TITLE
自定义域名问题

### ISSUE THREAD

**Issue by qr4d** [blackstorm/gitblog-feedback#1]
添加了自定义域名 blog.qr4d.com ，cname已经生效，访问时不会进入blog页面，而是自动跳转到下面这个网址
https://gitblog.io/?redirect_by=http://blog.qr4d.com/
需要做什么特殊设置么？
另外自定义域名支持ssl么？

**Comment by blackstorm** [comment]
Hello, I seen your blog is up now.

>需要做什么特殊设置么？

不需要，只需要解析到指定地址即可

>另外自定义域名支持ssl么？

支持全自动化的 SSL

**Comment by huwewa** [comment]
你好，我的域名在cloudflare , 我设置了一个 DNS only 的CNAME。子域名是 t.wywon.com访问 t.wywon.com 能跳转，但是跳转到的是 https://gitblog.io/?redirect_by=http://t.wywon.com/?ssp=1&setlang=en&cc=SG&safesearch=off 并没有跳到我在 gitblog.io 上的博客 。请教一下这是什么原因呢？Sent from my iPhoneOn Jan 20, 2024, at 01:03, 浩 ***@***.***> wrote:﻿
Hello, I seen your blog is up now.
