### ISSUE TITLE
微信公众号的图片显示异常问题

### ISSUE THREAD

**Issue by yestoday2009** [blackstorm/gitblog-feedback#2]
Hi，

我使用https://github.com/webclipper/web-clipper 对网页进行剪藏生成git issue，然后使用gitblog生成post。但在处理微信公众号文章时，遇到一个图片显示异常的问题。
在git issue里图片显示正常，我查看了下图片地址是在`camo.githubusercontent.com` 。但在gitblog的post里，地址变成了`mmbiz.qpic.cn/sz_mmbiz_png`，然后显示“此图片来自微信公众平台”。但直接用这个图片网址在浏览器打开是正常的。
烦请看下这个问题，谢谢！

**Comment by blackstorm** [comment]
Hi，我检查了源图片链接，确实来自微信。

<img width="236" alt="Snipaste_2024-01-25_14-46-03" src="https://github.com/blackstorm/gitblog-feedback/assets/13211110/2a170f39-3234-4b9b-885c-28b29257ccb1">

建议：**检查 Markdown 图片链接是否正确**

**Comment by yestoday2009** [comment]
> Hi，我检查了源图片链接，确实来自微信。
> 
> <img alt="Snipaste_2024-01-25_14-46-03" width="236" src="https://private-user-images.githubusercontent.com/13211110/299561855-2a170f39-3234-4b9b-885c-28b29257ccb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODAzNjEsIm5iZiI6MTcwNjE4MDA2MSwicGF0aCI6Ii8xMzIxMTExMC8yOTk1NjE4NTUtMmExNzBmMzktMzIzNC00YjliLTg4NWMtMjhiMjkyNTdjY2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEwNTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZTUzZWEzNjNiNzU1Y2U0MWM2YWNjZDA3OTFjNTkwYmYzMjExNmM4YTY0NzA4NDkyOTZkZDJkYmZiZGVlMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JCgyNCPLQlnZTgitRhQsT6bRlXyPMh_1kSj1XQRGlY0">
> 建议：**检查 Markdown 图片链接是否正确**

但git issue里的图片是
![image](https://github.com/blackstorm/gitblog-feedback/assets/3342008/6495892d-d0b6-4ee9-8db7-3df2f598ed3a)

**Comment by blackstorm** [comment]
> > Hi，我检查了源图片链接，确实来自微信。
> > <img alt="Snipaste_2024-01-25_14-46-03" width="236" src="https://private-user-images.githubusercontent.com/13211110/299561855-2a170f39-3234-4b9b-885c-28b29257ccb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODAzNjEsIm5iZiI6MTcwNjE4MDA2MSwicGF0aCI6Ii8xMzIxMTExMC8yOTk1NjE4NTUtMmExNzBmMzktMzIzNC00YjliLTg4NWMtMjhiMjkyNTdjY2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEwNTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZTUzZWEzNjNiNzU1Y2U0MWM2YWNjZDA3OTFjNTkwYmYzMjExNmM4YTY0NzA4NDkyOTZkZDJkYmZiZGVlMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JCgyNCPLQlnZTgitRhQsT6bRlXyPMh_1kSj1XQRGlY0">
> > 建议：**检查 Markdown 图片链接是否正确**
> 
> 但git issue里的图片是 ![image](https://private-user-images.githubusercontent.com/3342008/299634156-6495892d-d0b6-4ee9-8db7-3df2f598ed3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMzQyMTQsIm5iZiI6MTcwNjIzMzkxNCwicGF0aCI6Ii8zMzQyMDA4LzI5OTYzNDE1Ni02NDk1ODkyZC1kMGI2LTRlZTktOGRiNy0zZGYyZjU5OGVkM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMDE1MTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWU3MGVkY2FmMDFlNWY1NWUyMGQzOTliMjk1ZGYzN2UzNGQzNzBlM2VhOTA5OGUyNGRkZTA3ZjVhMjhjNzc0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3nepKr2jNC4wiEPs9AA88ZH1rOYrF021Nvju70yyBOY)

如果此文章更新过的话，存在一种可能是源未能成功同步，请问可以再次修改 issue 触发一下更新？
