### ISSUE TITLE
部分 markdown 格式显示异常

### ISSUE THREAD

**Issue by ryan961** [blackstorm/gitblog-feedback#3]
1. 下面 `<table>` 格式的内容无法显示出来

```
<table>
<tr>
<td width="20%"><strong>Title</strong></td>
<td>Test</td>
</tr>
</table>
```

2. Comments 的 markdown 格式显示紊乱

**Comment by blackstorm** [comment]
Thank you, Ryan!

The table and comments style display issue has been fixed and is now awaiting release.
