### ISSUE TITLE
Comment deletion not taking effect and  some proposals for improvement.

### ISSUE THREAD

**Issue by ryan961** [blackstorm/gitblog-feedback#4]
Hello, I have already removed the first two comments from the original issues section of my post located at https://ryan961-memo.gitblog.xyz/posts/2 .I have noticed, rather unusually,that those comments continue to appear below the post.

In addition, I have two suggestions for improvement:

1. The redirection links in the comments can directly redirect within gitblog under current repository.

2. Can the issues that are pinned in the original repository be pinned in gitblog, such as setting pinned labels of gitblog to the original issue?

**Comment by blackstorm** [comment]
Hi Ryan,

The comments remove fixed❤️ Please let me know if the comments continue to appear.

Also, thanks for the suggestions to improve redirect links and sync pinned issues. I will consider adding those features in the future.

I appreciate you taking the time to give feedback. Please let me know if any other issues come up!
