### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Daniel011011** [blackstorm/gitblog-feedback#5]
1. 能否考虑支持黑夜模式？或者页面上增加一个按钮支持
2. 能否考虑RSS链接的图标放在首页，方便阅读者
3. 能否支持置顶？在其他类似[项目](https://github.com/yihong0618/gitblog)处看到添加 labels （TOP）既可置顶
4. 能否考虑在 markdown 文件里添加标签（配合github action或者其他方法自动打标签），如果需要再去 Github Issues 页面手打，对于后期如果换平台，或者本地管理博客的markdown文件不太方便。实现方式可能类似于，文件开头添加下图的内容
![image](https://github.com/blackstorm/gitblog-feedback/assets/89135196/d70750ef-7336-4621-8201-03395b0fd601)

不太了解上述能否实现，也许一些建议不太符合用 issues 管理博客简洁的思路。只是一些建议供参考。

**Comment by blackstorm** [comment]
Hi @Daniel011011 

- 关于添加暗色模式和置顶功能，我会根据用户的反馈考虑是否增加。
- 添加 RSS 的图标是个好主意，已加入排期。
- 在 markdown 文件内添加标签，在用户编辑操作略微复杂，但是如果有更多用户反馈我会尝试加入进来。
- 关于导出方式：后期会设计一个导出按钮，可导出带有标签的 MD 文件，以适用于 Hugo Hexo 等文档风格。
