### ISSUE TITLE
how can i delete my blog  permanently

### ISSUE THREAD

**Issue by Mrgu2** [blackstorm/gitblog-feedback#7]
I've already deleted my issue in my repository, but it is still visible in gitblog. How can I fix it and delete it permanently?
My website address https://reine.vip 
the problem title: file upload

**Comment by blackstorm** [comment]
Hi Mrgu2,

Apologies for the delayed response. You can delete your blog by clicking the "Danger zone" tab.

<img width="321" alt="Snipaste_2024-11-06_16-06-46" src="https://github.com/user-attachments/assets/82d7668f-074b-4d1a-a758-aec051a22c73">
